name: Heartbeat Workflow

on: [push]

jobs:
  jobs-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v5

      - name: Print-anything
        run: echo "Heartbeat test"
